### PR TITLE
Randomize cards order; Add few hobbies

### PR DESCRIPTION
**Pull request by kee-reel**
Sorry for my code >_<
I don't have much experience with JS, so don't know a nice way to extract `hobby[0]` into a temp variable in the `map()` call :c

### CODE REVIEW

**Comment by kee-reel** [comment]
I thought that order randomization is kinda suits here because usually new hobbies are always appear at the end (even if they're cool and badass) and it would be better to spread them all over the place ╰( ͡° ͜ʖ ͡° )つ──☆*:・ﾟ

**Comment by SashaGraves** [comment]
Actually, I also planned something like this!! But then decided, that it kinda weird to use "closed cards" and "random card" at once. But why not, if we both thought of this!! 
Let me review =)

**Comment by SashaGraves** [comment]
Actually you did pretty nice! This is js, just go with the flow xD this structures suit well for React functional components.
Though I noticed other thing, and I did small demo PRs for you. Just in case you are curious =)

But this code is pretty fine to and we can merge it)

**Comment by kee-reel** [comment]
Your's is much better, want it in the repo! (ﾉ◕ヮ◕)ﾉ*:・ﾟ✧

**Pull request merged**
